resources:
  repositories:
    - repository: AzureTestingPOC
      type: gitHub
      endpoint: GitHubSang
      name: sanghung2/JavaProjectDemo
      ref: azure-pipeline
    - repository: PipelineTestingPOC
      type: git
      name: Testing Pipeline POC
      ref: main
      trigger:
        - main


pr: none
pool:
  vmImage: 'ubuntu-latest'
parameters:
  - name: pomFile
    type: string
    default: 'pom.xml'
stages:
  - stage: Build
    jobs:
      - job:
        displayName: Build and Run Tests
        steps:
          - checkout: self
          - checkout: AzureTestingPOC
          - powershell: |
              Write-Host "Running this pipeline"
            displayName: Running Script
